### ISSUE TITLE
在线安装后打开闪退

### ISSUE THREAD

**Issue by Livan-91** [xintd/xsgg#2]
在线安装后打开闪退，是需要登录Appstore验证ID么？

**Comment by yyyjk** [comment]
在线安装后打开闪退，爱思助手安装后提示输入id和密码，不知道有没有其他办法

**Comment by Livan-91** [comment]
> 在线安装后打开闪退，爱思助手安装后提示输入id和密码，不知道有没有其他办法

系统版本允许可以巨魔，不然就尝试其他软件吧
